/*
 * GoToSocial Swagger documentation.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: REPLACE_ME
 * Contact: admin@gotosocial.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace DotPub.DataContracts.Models
{
	/// <summary>
	/// 
	/// </summary>
	[DataContract]
	public partial class StatusContext : IEquatable<StatusContext>
	{
		/// <summary>
		/// Parents in the thread.
		/// </summary>
		/// <value>Parents in the thread.</value>

		[DataMember(Name = "ancestors")]
		public List<Status> Ancestors { get; set; }

		/// <summary>
		/// Children in the thread.
		/// </summary>
		/// <value>Children in the thread.</value>

		[DataMember(Name = "descendants")]
		public List<Status> Descendants { get; set; }

		/// <summary>
		/// Returns the string presentation of the object
		/// </summary>
		/// <returns>String presentation of the object</returns>
		public override string ToString()
		{
			var sb = new StringBuilder();
			sb.Append("class StatusContext {\n");
			sb.Append("  Ancestors: ").Append(Ancestors).Append("\n");
			sb.Append("  Descendants: ").Append(Descendants).Append("\n");
			sb.Append("}\n");
			return sb.ToString();
		}

		/// <summary>
		/// Returns the JSON string presentation of the object
		/// </summary>
		/// <returns>JSON string presentation of the object</returns>
		public string ToJson()
		{
			return JsonSerializer.Serialize(this, new JsonSerializerOptions() { WriteIndented = true });
		}

		/// <summary>
		/// Returns true if objects are equal
		/// </summary>
		/// <param name="obj">Object to be compared</param>
		/// <returns>Boolean</returns>
		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			return obj.GetType() == GetType() && Equals((StatusContext)obj);
		}

		/// <summary>
		/// Returns true if StatusContext instances are equal
		/// </summary>
		/// <param name="other">Instance of StatusContext to be compared</param>
		/// <returns>Boolean</returns>
		public bool Equals(StatusContext other)
		{
			if (ReferenceEquals(null, other)) return false;
			if (ReferenceEquals(this, other)) return true;

			return
				(
					Ancestors == other.Ancestors ||
					Ancestors != null &&
					Ancestors.SequenceEqual(other.Ancestors)
				) &&
				(
					Descendants == other.Descendants ||
					Descendants != null &&
					Descendants.SequenceEqual(other.Descendants)
				);
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
		{
			unchecked // Overflow is fine, just wrap
			{
				var hashCode = 41;
				// Suitable nullity checks etc, of course :)
				if (Ancestors != null)
					hashCode = hashCode * 59 + Ancestors.GetHashCode();
				if (Descendants != null)
					hashCode = hashCode * 59 + Descendants.GetHashCode();
				return hashCode;
			}
		}

		#region Operators

#pragma warning disable 1591

		public static bool operator ==(StatusContext left, StatusContext right)
		{
			return Equals(left, right);
		}

		public static bool operator !=(StatusContext left, StatusContext right)
		{
			return !Equals(left, right);
		}

#pragma warning restore 1591

		#endregion Operators
	}
}